### ISSUE TITLE
link to http://openmapkit.org is broken

### ISSUE THREAD

**Issue by fbeauchamp** [AmericanRedCross/OpenMapKitServer#10]
I get this message when I want to visit the website : 

    404
    There isn't a GitHub Pages site here.
    If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.
     
    GitHub Status — @githubstatus

**Comment by dalekunce** [comment]
We are currently building out the site. Look for it to be online sometime in January.

**Comment by sabarivasagan** [comment]
![site not found github pages 2016-09-10 10-46-43](https://cloud.githubusercontent.com/assets/13609681/18408144/6728a3ba-7744-11e6-94c5-cd48a78734b2.png)

**Comment by sabarivasagan** [comment]
i also had this same issue...

**Comment by sabarivasagan** [comment]
what i need to do...(For host my web page)

**Comment by danbjoseph** [comment]
http://openmapkit.org/ is loading for me. @sabarivasagan can you check again and see if there is still an issue? It might have been a temporary problem with GitHub's services.

**Comment by sabarivasagan** [comment]
Yes.. loading now...I solved this issue
