### ISSUE TITLE
Windows OS Computer

### ISSUE THREAD

**Issue by KThillainathan** [AmericanRedCross/OpenMapKitServer#106]
Can I install OpenMapKit Server in Windows OS Computer?

**Comment by dalekunce** [comment]
I'm sure its possible but I don't have a windows computer to test.

**Comment by mojodna** [comment]
@KThillainathan your best option is to run the Docker container, since that'll paper over any Unix-isms (likely present): `docker run quay.io/americanredcross/openmapkitserver`

**Comment by KThillainathan** [comment]
If you have any help / tutorials links for install OpenMapKit Server in Windows OS Computer, Pl send me

**Comment by mojodna** [comment]
You'd be the first that we'd know of, so if you get it working, please report back!
