### ISSUE TITLE
Run bootstrap.sh on Ubuntu 16.04?

### ISSUE THREAD

**Issue by samuel-watson** [AmericanRedCross/OpenMapKitServer#107]
bootstrap.sh does not run on Ubuntu 16.04. Line 83 can be modified for python 3 to run it, however I get the error "Unsupported release: 16.04" and I can't work out what is throwing the error. Are there any modifications that can be made to get this script to run on 16.04?

**Comment by dalekunce** [comment]
@samuel-watson we haven't moved to support 16.04 yet. The amount of work to port it is large at this time and not on our current road map. Please continue to user Ubuntu 14.04.
