### ISSUE TITLE
Export OSM Micro App

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitServer#15]
We want a simple app where we can apply submit time and username based filters, get that filtered and aggregated OSM XML file.

We need to:

1. Download for JOSM
2. Open in iD
3. Try to directly submit to OSM

**Comment by mojodna** [comment]
To be clear, these are exports produced from OMK surveys?

**Comment by hallahan** [comment]
Correct. Now that I have completed #9 that aggregates and filters OSM submissions, we want to see the aggregation, and do filtering, on a map. We then will have buttons to download the aggregate OSM XML, and next pass, we can have a button to open the OSM XML in iD via the McLennan hack. Simplicity.

@danielduhh will help build a simple dashboard with a filter panel and a tag info panel. I will help with the OSM -> GeoJSON, so we don't have to do anything too deep with MapboxGL JS.

The goal is to treat this as a micro-app that takes only a few days at max to complete. We will need a green light from @dalekunce and @jharpster, as well as a time for completion.

This can live as a standalone front-end [Angular Material Design](https://material.angularjs.org/latest/) app, and this is especially good, since @danielduhh has been actively working with this framework and is fresh with it.

This will be the __exit point__ for OSM data from OpenMapKit.

https://github.com/AmericanRedCross/OpenMapKitServer/tree/master/public/export-osm

**Comment by dalekunce** [comment]
Before we spec out any new front ends. I want a solid conversation to be had about one front end framework/library for all of the new UI/UX being created. These is less to do with the technology and more to do about support for the system later on. I don't have favorite but I don't want a mix up of many different javascript frameworks for very simple apps. As I see it there are a few options:

- Angular
- React
- Vanilla Javascript

**Comment by hallahan** [comment]
## An Alternative

We forked GeoForce's GeoAngular to be a bit more generic as a basis for dashboardy webmap viewer type apps. @danielduhh has also recently put in mapbox-gl-js as a viewer instead of Leaflet. Because it has stateful routing, a filter panel, basemaps panel, info panel, and what not, this could be a good starting point. This approach would have a similar feel to GeoAngular, and it would probably the least LOE option.

**Comment by mojodna** [comment]
When we talked last week, we determined that this component is the only piece of UI that's being built from scratch (the export UI might be, but the HOT Export Tool is a strong contender), so there's nothing else new for it to harmonize with. In other words, if SpatialDev decides that Angular is the right answer for them, that gets a :+1: from me.

**Comment by hallahan** [comment]
After extended discussion with @mojodna and @jharpster at Stamen, we've decided this piece should actually directly use iD. We will augment iD in the following ways:

1. Filter UI for OMK Server timestamp and user filters.
  * This can of course be done client side instead, but we have the node endpoints working, so that can be a later todo.
2. Download OSM to JOSM button.
3. Dropdown menu to choose what ODK form's submission data to look at.
4. Submit to POSM APIDB / Macrocosm

cc/ @rgwozdz @danielduhh

**Comment by hallahan** [comment]
This has been implemented as a custom version if iD. Work is being tracked here:

https://github.com/AmericanRedCross/id/tree/omk
