### ISSUE TITLE
Sample Forms

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitServer#21]
We need a decent collection of sample XLS and XForms to be provided in the server by default. These should be good starters for people to make their own forms.

**Comment by dalekunce** [comment]
cc @robertbanick @danbjoseph

**Comment by hallahan** [comment]
A solid collection of sample forms are now included with the project.

https://github.com/AmericanRedCross/OpenMapKitServer/tree/master/public/forms
