### ISSUE TITLE
ODK CSV Export

### ISSUE THREAD

**Issue by adissadis** [AmericanRedCross/OpenMapKitServer#22]
Hi all,

I success build OMK Server in my local server and right now I'm curious about how to download all the result from field mapping because all the finished form that i uploaded to server have unique folder name with .json and .xml file inside the folder.

Is OMK server also have capabilities to append/combine all the submitted form as one csv file? If yes, would you guys tell me how to do it? Thanks

**Comment by hallahan** [comment]
Currently the server can combine all submissions into:

1. A single [OSM XML](https://github.com/AmericanRedCross/OpenMapKitServer/blob/4758797fafbc5e419673860f38a9c8cc69737e43/odk/odk-routes.js#L38) file.
2. A single [JSON file](https://github.com/AmericanRedCross/OpenMapKitServer/blob/4758797fafbc5e419673860f38a9c8cc69737e43/odk/odk-routes.js#L36) of the ODK data.

Here are some examples of accessing the OSM API. Sorry we're a bit sparse on docs, and help would be appreciated.

https://github.com/AmericanRedCross/OpenMapKitServer/issues/9#issuecomment-168109187

Would OSM XML or JSON suffice? What specifically do you want CSV for?

**Comment by dalekunce** [comment]
@hallahan csv download for the ODK part of the submission should already be in SimpleODK do you know the endpoint of that?

**Comment by hallahan** [comment]
I don't see any aggregation endpoints. They rely on backends like Github, so I assume they use Github API to traverse results for their frontend.

**Comment by hallahan** [comment]
After discussion, we're planning out building a UI that includes a CSV export. I'm going to rename this issue, and we will track the project for CSV functionality here.

**Comment by hallahan** [comment]
Basic functionality is implemented. 

![screenshot 2016-02-18 17 49 20](https://cloud.githubusercontent.com/assets/556367/13164265/c888c536-d668-11e5-9277-b8f0834e450b.png)

**Comment by hallahan** [comment]
First iteration done

**Comment by adissadis** [comment]
Wow thank you @hallahan for bring this feature! I will try this feature now.

**Comment by hallahan** [comment]
take a look at the urls in the screen shot to see how to load the data. we will be building a form view showing what forms are there allowing you to click into the right data view
