### ISSUE TITLE
Check that XLS Form is xlsx format

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitServer#23]
pyxform only understands xlsx format. It does not understand xls format. Make sure that it checks for this and provides an informative error.

**Comment by dalekunce** [comment]
Out of scope for now but I would like to add support for xls forms.

**Comment by hallahan** [comment]
I don't think the xlsx reader library pyxform depends up can do it AFIK

**Comment by hallahan** [comment]
![screenshot 2016-02-18 11 58 40](https://cloud.githubusercontent.com/assets/556367/13156397/272a92fe-d637-11e5-81a5-43e4577855c1.png)
