### ISSUE TITLE
Simple Auth

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKitServer#24]
sometimes you want very basic auth to protect the site if you put it up publically anywhere.

Add support for simple username/pass for one user for the entire site. No need to do user management and all that jazz.

This should be configurable to be default off and then turned on via posm-build install

**Comment by hallahan** [comment]
I'm thinking a simple json web token middlewhare. We could specify a user name and password in `settings.js`.

**Comment by hallahan** [comment]
Ok, I've got a simple basic auth implementation in now.

You enable authentication for OMK routes (except for JavaRosa) by adding the following in your `settings.js`:

```js
auth: {
        user: 'username',
        pass: 'password'
}
```

**Comment by hallahan** [comment]
Pushing up to omkserver.com...

**Comment by hallahan** [comment]
I found some problems. We have to be very specific and only lock down the pages and the ODK submissions routes. Locking down the forms causes problems with the SimpleODK OpenRosa modules `/formList`, because they make HTTP requests internally (they were never intended for auth).

**Comment by hallahan** [comment]
Alright, deployed, seems to be working fine. Closing.
