### ISSUE TITLE
Download image attachments in bulk

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#29]
if images have been collected as part of the ODK portion of a survey. is there a way to get a single download of all the image files?

**Comment by hallahan** [comment]
They are in the submissions directory. There is no endpoint that finds the images and makes a zip, but that would be straightforward.

**Comment by hallahan** [comment]
We could make a very simple bash script to do this and wrap it in an endpoint. After field work type of task.

**Comment by danbjoseph** [comment]
as noted in #88, there's currently no support for `image` type questions
so support for image type questions
and the ability to download all images for a form as a zip

**Comment by danbjoseph** [comment]
`image` question type
http://xlsform.org/#question-types

**Comment by mojodna** [comment]
The root cause of @emilyeros's breakage (explained in #88) was a space in the filename, not anything to do with image attachments.

**Comment by mojodna** [comment]
How (image) attachments are currently treated:

![image](https://cloud.githubusercontent.com/assets/45/23679378/939fcbba-033c-11e7-8de5-8f74e64f2e2b.png)

@danbjoseph when downloading all images for a form as a zip does it make sense to also include the JSON and XML responses (the XForm submissions)? (If so, it also makes sense to preserve the directory structure.) Thoughts?

**Comment by danbjoseph** [comment]
i think a zip of just the images is fine. i think most users would probably end up doing some sort of mail merge using the csv download and a single folder of all the images. if a user is doing something with the individual json and xml, they probably are advanced enough to just copy the directory from the server. including those files in the image zip download would likely confuse some users.

**Comment by mojodna** [comment]
![image](https://cloud.githubusercontent.com/assets/45/24484538/93a43622-14b3-11e7-8a65-9e1dc420823c.png)
