### ISSUE TITLE
Form upload GUI

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKitServer#3]
Need a simple GUI to upload forms to the server. Ideally this would be a drag and drop interface.

**Comment by hallahan** [comment]
I'm working on this feature in the [pyxform](https://github.com/AmericanRedCross/OpenMapKitServer/tree/pyxform) branch.

To convert a XLSForm to an XForm, pyxform must be installed. I'm following a similar to approach found in [cadasta-provider-ona](https://github.com/Cadasta/cadasta-provider-ona).

It looks like in Cadasta, we're using the tool [xls2json.py](https://github.com/Cadasta/cadasta-provider-ona/blob/a01d8c2e108edfd81ed799e20a2d842d796bde94/pyxform/pyxform/xls2json.py), and we're calling it from the NodeJS module [PythonShell](https://github.com/Cadasta/cadasta-provider-ona/blob/a01d8c2e108edfd81ed799e20a2d842d796bde94/index.js#L244). After setting up a git submodule and getting this pyxform code in here and installed, that tool works fine.

The problem is that we need to get [xls2xform.py](https://github.com/XLSForm/pyxform/blob/master/pyxform/xls2xform.py) working instead, which isn't quite as simple as xls2json... After running a `pip install`, I'm trying to run the tool via command line:

```
python pyxform/pyxform/xls2xform.py ~/code/OpenMapKitServer/public/forms/Gampaha_survey_v3.xlsx ~/Desktop/test.xml
```

I'm getting the following error:

```
Traceback (most recent call last):
  File "pyxform/pyxform/xls2xform.py", line 7, in <module>
    import builder
  File "/Users/njh/code/OpenMapKitServer/ODK/pyxform/pyxform/builder.py", line 8, in <module>
    from survey import Survey
  File "/Users/njh/code/OpenMapKitServer/ODK/pyxform/pyxform/survey.py", line 12, in <module>
    from pyxform import constants
ImportError: No module named pyxform
```

After groking the google, I'm finding other people having similar issues:

https://groups.google.com/forum/#!topic/opendatakit/5ui0l6ZE74Q

One person suggested that we install pyxform via

```
pip install pyxform
```

Then, we can run the tool like this:

```
$ cd /usr/local/lib/python2.7/site-packages/pyxform; 
$ python xls2xform.py ~/Desktop/Form.xlsx ~/Desktop/Form.xml;
```

Unfortunately, `pip install pyxform` isn't working. Not surprisingly, it's depending on compiling the C library `libxml2`. Something is off with where the pip package is looking for require system headers...

```
    In file included from src/lxml/lxml.etree.c:239:
    src/lxml/etree_defs.h:9:10: fatal error: 'libxml/xmlversion.h' file not found
    #include "libxml/xmlversion.h"
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Ki9YU9/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-QmaH4b-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Ki9YU9/lxml
```

Further, I'm seeing that the library uses some Java JARs, so I'm assuming I'm going to have to make sure the target system has some form of Java installed as well:

https://github.com/XLSForm/pyxform/tree/master/pyxform/odk_validate

**Comment by hallahan** [comment]
It looks like OS X 10.11 does not come with libxml2 installed automatically. I went to libxml2's website, downloaded the source code, configured, compiled, and installed it. It's now living happily in `usr/local/`. Still, running `pip install pyxform` still gives me the same problem. It looks like pip tries to compile libxml2 itself and install it in a custom location. Something is wrong with pip's installation on OS X.

**Comment by hallahan** [comment]
I tried to `sudo pip install pyxform` on ubuntu, and I ran into further problems:

```
building 'lxml.etree' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/lxml

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

src/lxml/lxml.etree.c:4:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-oc5QBo-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/lxml
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

I'm getting different libxml2 problems, but they are libxml2 problems... 

```
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

src/lxml/lxml.etree.c:4:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-oc5QBo-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/lxml
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-oc5QBo-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/lxml
```

**Comment by hallahan** [comment]
I'm able to get `xls2json.py` to work on Ubuntu 14.04 by following the [following instructions](https://github.com/XLSForm/pyxform#running-pyxform-as-a-python-script):

1. Clone https://github.com/XLSForm/pyxform.git

2. `pip install xlrd`

3. `python pyxform/xls2xform.py path_to_XLSForm output_path`

It would be good to get this working on OS X 10.11, but at least we have a way to get it working on Ubuntu.

**Comment by hallahan** [comment]
I'm able to get `xls2xform.py` working on OS X 10.11.

First, install Java if you haven't already. pyxform is really all about the JavaRosa.

http://www.oracle.com/technetwork/java/javase/downloads/index.html

With Java installed, you need to change a line of code:

https://github.com/XLSForm/pyxform/blob/c418ad9cba065fa8b8723ff24f66954c70374c6b/pyxform/survey.py#L12

In `survey.py`, change:

```
from pyxform import constants
```

to

```
import constants
```

With that, `xls2xform.py` is working on OS X. I'm going to fork pyxform and submit a pull request for this. I'll also have the git submodule refer to the forked repo with this fix.

**Comment by hallahan** [comment]
I have now gotten pyxform to work on an Ubuntu EC2 that is built via posm-build. I'll need to modify the build script accordingly with the added dependencies this branch introduces.

**Comment by hallahan** [comment]
OK, we've got XLS form uploads working now.

the path to the upload page is:

    <hostname>/public/upload-form/
