### ISSUE TITLE
Material Design Lite CSS

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitServer#32]
We want to use [Material Design Lite](https://www.getmdl.io/).

There are many ways to bring it in as a package like npm and bower, but let's just directly include it in the Jekyll project so we don't have yet another dependency.

We do want to tweak the CSS to have the OpenMapKit Look and feel. Take a look at OpenMapKit iD editor. We want to match those colors for the top bar and other elements.

![screenshot 2016-02-26 11 55 45](https://cloud.githubusercontent.com/assets/556367/13363755/fc4d6670-dc7f-11e5-9d98-a977e2185991.png)

[OpenMapKit Icon](https://github.com/AmericanRedCross/iD/blob/omk/dist/img/ic_omk_nobg-web.png)

![ic_omk_nobg-web](https://cloud.githubusercontent.com/assets/556367/13363817/53b470b6-dc80-11e5-9bee-e8d0ee4e7fff.png)

OSM Green: `#7ebc6f`
OSM Light Green: `#ff8bd27c`
OSM Dark Green: `#83b26e`

**Comment by hallahan** [comment]
@rrlara Could you add the OMK icon to the header of each Jekyll page?

**Comment by rrlara** [comment]
Done. Added Icon on the header.
