### ISSUE TITLE
Forms Page

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitServer#33]
We need a page showing the forms available. This endpoint shows a list of forms:

`/formList?json=true`

An example of this endpoint's response:

```json
{
  "xforms":{
    "attributes":{
      "xmlns":"http://openrosa.org/xforms/xformsList"
    },
    "xform":[
      {
        "name":"Building Placeholders",
        "formID":"building_placeholders",
        "hash":"md5:0e13893e49a5e567f864de01de6ab2c0",
        "downloadUrl":"http://localhost:3210/omk/data/forms/building_placeholders.xml"
      },
      {
        "name":"Buildings",
        "formID":"buildings",
        "hash":"md5:007b8707e0bb9c2c6ef53502df915ae7",
        "downloadUrl":"http://localhost:3210/omk/data/forms/buildings.xml"
      },
      {
        "name":"Buildings with POIs",
        "formID":"buildings_with_pois",
        "hash":"md5:b4d9f02b7fd41c52004c0889fa8b4d37",
        "downloadUrl":"http://localhost:3210/omk/data/forms/buildings_with_pois.xml"
      },
      {
        "name":"Mobile Money Agent",
        "formID":"mobile_money",
        "hash":"md5:1431de362053a476a9778bbae349b614",
        "downloadUrl":"http://localhost:3210/omk/data/forms/mobile_money.xml"
      },
      {
        "name":"Points of Interest",
        "formID":"pois",
        "hash":"md5:cfa8c4a0e95aa98047f33d9c5d946831",
        "downloadUrl":"http://localhost:3210/omk/data/forms/pois.xml"
      }
    ]
  }
}
```

We want to see this info in a Material Design card layout of similar size to the PSOM home page:

![screenshot 2016-02-26 12 07 41](https://cloud.githubusercontent.com/assets/556367/13364042/92a5ee5c-dc81-11e5-8740-7e79603b760e.png)

A given form should show up in a card about that size. We probably want the little bottom tab part actually be on top and be the `name`. In each card we should see:

1. Name
2. Number of Submissions
3. Form ID
4. XLS / XML download URLs

We want to link the `name` field to the `/omk/pages/submissions` page so that the user can see the submissions for the given form and download a CSV.

Lastly, we want to have a link to __iD__ and __Upload Form__ in the top header.

**Comment by hallahan** [comment]
We are going to want a few links that will function as the actions with the cards. those will be:

1. View Submissions
2. Edit OSM
3. Download XLS Form
4. Download XForm XML

I'm thinking the _View Submissions_ and _Edit OSM_ actions should be written out, and the Download XLS & Download XForm should be in that triple dot overflow button.

**Comment by rrlara** [comment]
Done.
