### ISSUE TITLE
Form Upload: DnD & File Name

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitServer#38]
<img width="708" alt="screenshot 2016-03-04 11 12 23" src="https://cloud.githubusercontent.com/assets/556367/13537483/ffc89660-e1f9-11e5-89d8-8ffa8a9a9867.png">

1. The user should be able to drag and drop a file in the box.
2. After a file has been selected, show the name of the file so that the user knows that it is staged to be submitted.

**Comment by rrlara** [comment]
This is implemented.
