### ISSUE TITLE
Failed when trying to run npm install

### ISSUE THREAD

**Issue by adissadis** [AmericanRedCross/OpenMapKitServer#4]
Hi,

I want to try OMK server in my virtual machine (Ubuntu Server 15). And when i want to run `npm install` i got these error:

![image](https://cloud.githubusercontent.com/assets/2520159/11677152/36c59f58-9e6d-11e5-9f6a-3f11bc86f723.png)

Do you guys know what's the problem? Did i missing something that i need installed before i run `npm install`?

My position is fresh install Ubuntu Server 15.04 and just installed npm for run `npm install`

**Comment by danbjoseph** [comment]
i had a similar looking problem (on Ubuntu 14.04) and solved it by running:
`sudo apt-get install build-essential`

**Comment by hallahan** [comment]
Cool, I'll add that to the instructions.

**Comment by hallahan** [comment]
Also, though you are probably fine, your NodeJS version is old. Our baseline version is 4.2.2
