### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#45]
![screen shot 2016-03-10 at 12 05 18 pm](https://cloud.githubusercontent.com/assets/4806884/13677662/f61bac9c-e6b8-11e5-8bd2-895c882bd407.png)
download xls goes here:
http://omkserver.com/omk/data/forms/colombia_buildings.xlsx
which returns: 

```
Cannot GET /omk/data/forms/colombia_buildings.xlsx
```

**Comment by danbjoseph** [comment]
or... that file just isn't there. the link would work otherwise.

**Comment by hallahan** [comment]
Oooo. The form got re-uploaded but got capitalized. It is there, but it is found at the following path:

http://omkserver.com/omk/data/forms/Colombia_buildings.xlsx

I need to make things case insensitive, at least for that data dir.

**Comment by hallahan** [comment]
Actually, if implement #46, this problem will be solved.

**Comment by mojodna** [comment]
Fixed by implementing a fix for #46.
