### ISSUE TITLE
Handle Bad Manifests Gracefully

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitServer#58]
Currently the `/omk/deployments` endpoint is down on Dale's server. We're getting

```
{
status: 500,
msg: "Unexpected token ]",
err: { }
}
```

This is because the JSON in one of the manifests is formatted improperly. Handle this gracefully so the rest of the deployments continue to show up.

cc/ @dalekunce

**Comment by dalekunce** [comment]
which one, we are using this right now. @hallahan

**Comment by hallahan** [comment]
`vahun` is the culprit.

I'm going to make it so that the deployment will still work even if you outright omit a `manifest.json`, that way you don't have to spend a ton of time dealing with it.

I'll also make it work if the manifest is bogus -- just show the contents of the deployment without manifest.

The only use of the manifest is to have a pretty title and description. We originally though we would need it for other things, but it's proven less useful than we thought (a good thing).

**Comment by hallahan** [comment]
Vahun's manifest.json was missing a value in the bbox:

```json
{
	"description": "Vahun",
	"contents": {
		"tiles/vahun.mbtiles": {
			"maxzoom": 20,
			"source": "http://tile.openstreetmap.org/{z}/{x}/{y}.png",
			"minzoom": 12,
			"type": "MBTiles",
			"name": "MBTiles Export"
		}
	},
	"name": "vahun",
	"bbox": [-10.51123, 8.05673, -10.49776, 8.06834, ],
	"title": "Vahun"
}
```
