### ISSUE TITLE
select multiple treated as geo-point in data on server

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#59]
a select_multiple with answers like
1    Meat
2    Poultry
3    Fish
4    Fruit
5    Vegetables
97    Other
98    Refused
99    Don't Know

mostly has data like

```
"marktype": "3 4 5",
```

but will also appear like 

```
"marktype": {
      "latitude": 1,
      "longitude": 3,
      "altitude": 4,
      "precision": 5
    },
```

(links to example occurrences are on April 4 in the posm channel in the openmapkit slack)

**Comment by danbjoseph** [comment]
**i think this affects 1,200+ submissions across 4+ surveys**

- same issue, different question

`Liberia_Community_Survey_Mar2016_MF_v1/7964a442-178d-4c60-ba03-8e50ee554e87`
```
  "b": {
    "intro": 2,
    "intro_fail": {
      "latitude": 1,
      "longitude": 3,
      "altitude": 4,
      "precision": 97
    },
```
- same issue, multiple questions (marktype question unaffected)

`Liberia_Community_Survey_v18/1576a84d-94f5-4c97-92a2-1401ebe6f713/data.json`
```
"n": {
    "treat_mult": {
      "latitude": 5,
      "longitude": 9,
      "altitude": 10,
      "precision": 12
    }
  },
...
"s": {
    "birth_mult": {
      "latitude": 5,
      "longitude": 9,
      "altitude": 10,
      "precision": 13
    }
  },
```


- other examples

```
Guinee_Sondage_Communautaire_V1-4-7/3c4a90ce-0522-476d-97fc-6fb37700ce7f
Guinee_Sondage_Communautaire_V1-4-7/3eb38179-9b4b-4280-8ec4-52a9a609d498
Guinee_Sondage_Communautaire_V1-4-7/40c71a0a-4718-4980-b76d-cbdec7bee638
Guinee_Sondage_Communautaire_V1-4-7/423cde52-77ce-48c4-a9a9-8f2644d08169

Guinee_Sondage_Communautaire_V1-4-3/fcbd76ce-82f9-4dcd-8fb3-92ad70ba384d
Guinee_Sondage_Communautaire_V1-4-3/f6db9911-c292-4c0f-9b98-2bc2219499d3
Guinee_Sondage_Communautaire_V1-4-3/f6dfce27-2fbe-406b-9a2f-a9af58dbd354
Guinee_Sondage_Communautaire_V1-4-3/fb071755-52ce-441b-a829-178c8e58ef2a

Liberia_Community_Survey_v18/07fd73af-d61b-4742-b1f4-a1e303f22130
Liberia_Community_Survey_v18/0b5ca53a-fc60-4699-9b1b-328e4373ca83
Liberia_Community_Survey_v18/0f9a86f8-239a-43b3-be9c-f1de8453dfb6
Liberia_Community_Survey_v18/11f7b35f-1c07-4b46-bba9-4a7a393aa708
```

**Comment by danbjoseph** [comment]
may just be in the JSON. the XML might be okay. 

http://omkserver.com/omk/data/submissions/Liberia_Community_Survey_Mar2016_MF_v1/7964a442-178d-4c60-ba03-8e50ee554e87/data.json
&
http://omkserver.com/omk/data/submissions/Liberia_Community_Survey_Mar2016_MF_v1/7964a442-178d-4c60-ba03-8e50ee554e87/data.xml

**Comment by hallahan** [comment]
Should be a simple fix. A reminant of Simple ODK code.

**Comment by danbjoseph** [comment]
- zip attached ( [issue59.zip](https://github.com/AmericanRedCross/OpenMapKitServer/files/657517/issue59.zip) ) with form xlsx, xform xml, and an example data xml submission that is converted incorrectly
- question with name `intro_fail` is a `select_multiple` with the following choices:
```
1	Skip the entire introduction
2	Paraphrase the introduction
3	Misrepresent the project or the goal of the Red Cross
4	Fail to introduce himself
97	Other
```
- [xform-to-json](https://www.npmjs.com/package/xform-to-json) is sometimes interpreting this in submission data as a geopoint question
- as used in [process-submission.js](https://github.com/AmericanRedCross/OpenMapKitServer/blob/832066dff7b43ae197ca8d334c964ed2eb8665f3/api/odk/middlewares/process-submission.js)
