### ISSUE TITLE
character encoding issues

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#61]
**Special characters are garbled in the json data on the server.**

_Mapper_registration_v1-0-2/44d28929-b177-4169-89db-1f1dc639895d/data.json_

```
"FIRST_NAME": "Saa CÃ©lestin",
```

_Mapper_registration_v1-0-2/912774e0-005f-4ae7-9404-6b8338d1498d/data.json_

```
"QUARTIER_OU_DISTRICT": "KÃ¨nÃ¨ma",
```

_Mapper_registration_v1-0-2/1fae7871-0608-4c5d-9748-b3c33066b8bd/data.json_

```
  "REGION_NAT": "Basse guinÃ©e",
```

**Comment by hallahan** [comment]
I see. The XML version is fine. Something funky with turning that XML to JSON.

http://omkserver.com/omk/data/submissions/Mapper_registration_v1-0-2/1fae7871-0608-4c5d-9748-b3c33066b8bd/data.xml

**Comment by hallahan** [comment]
It's not `fs.writeFile`, because that defaults to UTF-8

https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback

**Comment by hallahan** [comment]
I think the issue is in xform-to-json

https://github.com/digidem/xform-to-json

Perhaps xml2js is not doing things in utf-8?

https://github.com/Leonidas-from-XIV/node-xml2js

Requires further investigation.

**Comment by mojodna** [comment]
This looks like it's actually a Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=438464

If I use `curl` or download the JSON, things look copacetic.

@danbjoseph please re-open if this is causing problems and isn't just aesthetic when viewed in a browser.
