### ISSUE TITLE
Deployment Provisioning

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitServer#7]
This is the master issue of the server component regarding the provisioning of data for a field deployment.

Below is the drawing from the kickoff meeting describing how a deployment is abstracted. 

![deployment-provisioning](https://cloud.githubusercontent.com/assets/556367/11859393/36151fea-a41f-11e5-8ff6-2b4371853c55.jpg)

OpenMapKit Server will provide all of the proper metadata needed by OpenMapKit Android to find and retrieve data associated with a deployment. The actual data will be served as static assets, and metadata for a specific deployment will reside in a `manifest.json` file within the directory of the deployment.

The actual OSM data in the deployment such as OSM XML and MBTiles will be generated by [posm](https://github.com/AmericanRedCross/posm).

Work on this feature will be in the [deployment branch](https://github.com/AmericanRedCross/OpenMapKitServer/tree/deployment).

**Comment by hallahan** [comment]
See names of stuff
https://github.com/fieldpapers/fieldpapers/issues/195

**Comment by dalekunce** [comment]
I think this will eventually live in [posm-deployment](https://github.com/AmericanRedCross/posm-deployment) or potentially in a posm-deployment-server component that still needs to be developed.

**Comment by hallahan** [comment]
I think there are two parts to the deployment process. We want all communication with OpenMapKit Android to be with OpenMapKit Server, and we want the deployment itself to be a service with a job queue.

__OpenMapKit Server__ is responsible for serving the Android app the metadata and links to files in the `deployments` directory. This includes providing the manifest data as well as the files applicable for a given deployment.

[__posm-deployment__](https://github.com/AmericanRedCross/posm-deployment) is a service responsible for watching for changes in the manifest files and executing jobs to create  prescribed OSM and MBTiles files.

Since [__posm-deployment__](https://github.com/AmericanRedCross/posm-deployment) doesn't actually exist yet, this separation is really nice. We can go ahead and manually put files in the right place in the `deployments` directory, and OpenMapKit Server will serve those files to OpenMapKit Android as if posm-deployment did it's job. I can move forward with these files and begin building UI and a `DeploymentDownloader` on the Android app.

Also, if posm-deployment were to ever crash, OpenMapKit Server will continue as usual and continue serving deployments that have been previously generated.

**Comment by dalekunce** [comment]
@hallahan all makes sense to me.

**Comment by mojodna** [comment]
@hallahan which pieces run in the cloud and which run on the portable server?

**Comment by hallahan** [comment]
I want the deployment mechanism to be identical for cloud and portable server. The node app serves files in a public directory, the manifest json, with a minimal API. This should work the same in the cloud. 

We could write synchronization code between cloud and posm, but I haven't gotten there yet.

**Comment by mojodna** [comment]
How do those files get into the public directory / where do they come from / what are they?

**Comment by hallahan** [comment]
Getting them into the directory is a manual process at the moment. Creating that automated mechanism that reads the manifest file to generate files has yet to be built. I'd like to figure that part out with you Thu / Fri.

**Comment by mojodna** [comment]
What are the files? (More than just `manifest.json`? Is that described somewhere?)

**Comment by mojodna** [comment]
* OSM XML (including metadata? any caveats around this?)
* MBTiles (how many different styles?)
* `manifest.json`

**Comment by mojodna** [comment]
(I'm assuming there are forms in here somewhere)

**Comment by hallahan** [comment]
Correct, OSM XML and MBTiles go here:
https://github.com/AmericanRedCross/OpenMapKitServer/tree/master/public/deployments/Arcade%20Creek

Forms go here:
https://github.com/AmericanRedCross/OpenMapKitServer/tree/master/public/forms

You can upload forms here:
https://github.com/AmericanRedCross/OpenMapKitServer/blob/master/public/upload-form/index.html

The actual API for deployments is here:
https://github.com/AmericanRedCross/OpenMapKitServer/tree/master/deployments

**Comment by hallahan** [comment]
A sample response from `http://<server>/deployments` loos like

https://gist.github.com/hallahan/d4f3c54167e4403c53bc

This will need to change, because I need file sizes and file names to go along with the urls. I'm thinking I want to group them in an JSON object by type (OSM & MBTiles) for convenience as well.

**Comment by hallahan** [comment]
Regarding metadata for OSM XML, I haven't really found the need for that yet.

For MBTiles, I'd like the app to accept whatever it is given. At least 1 for satellite and 1 from tessera/mapnik.

**Comment by hallahan** [comment]
We're getting help on this API from @rgwozdz. Welcome!

**Comment by hallahan** [comment]
@rgwozdz Could you PR when you're ready to merge in?

**Comment by rgwozdz** [comment]
Submitted PR.

On Jan 16, 2016, at 7:33 AM, Nicholas Hallahan <notifications@github.com<mailto:notifications@github.com>> wrote:


@rgwozdz<https://github.com/rgwozdz> Could you PR when you're ready to merge in?

**Comment by hallahan** [comment]
This will have slight refactors as we go, but for the most part, this is solid. Closing.
