### ISSUE TITLE
duplicate names of .osm files

### ISSUE THREAD

**Issue by eoglethorpe** [AmericanRedCross/OpenMapKitServer#81]
in a survey recently conducted with ~580 submissions, ~20 contained duplicate names of .osm files.

Although the top level UUID file names were distinct, when I attempted to pull all .osm files into a single directory there were ~20 duplicate name conflicts

**Comment by dalekunce** [comment]
mmm, are all the versions of OMK up to date?

**Comment by eoglethorpe** [comment]
I believe so - my installation shows v0.5.0

**Comment by danbjoseph** [comment]
Can you please clarify?

OpenMapKitServer is at v0.4.0 and OpenMapKit (the android app) is at v1.1 in both the app store and on the [releases page](https://github.com/AmericanRedCross/OpenMapKitAndroid/releases) for the project repo

**Comment by eoglethorpe** [comment]
I think this is part of a larger conversation we're having with @hallahan... will post back any findings

**Comment by hallahan** [comment]
This is an issue with Android, and yes your app is out of date. All you need is to update.

**Comment by hallahan** [comment]
Is this resolved? @eoglethorpe

**Comment by eoglethorpe** [comment]
Yes @hallahan
