### ISSUE TITLE
'download csv' gives page html not the data

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#82]
![screen shot 2016-08-01 at 9 52 20 am](https://cloud.githubusercontent.com/assets/4806884/17296255/3eaa5310-57ce-11e6-8552-39f8ee73092a.png)

**Comment by hallahan** [comment]
Just check on this and duplicated the bug. This is a new bug that was not present before, we'll have to track down when this gets introduced.

For the time being, you can "View CSV" and copy paste the contents into your spreadsheet.

**Comment by hallahan** [comment]
During last revamp of the UI, this jQuery selector got broken:

https://github.com/AmericanRedCross/OpenMapKitServer/blob/2f6aaec7531f4e8562b1b18a12d4fa1ef2ab1832/jekyll/js/submissions/index.js#L134

We need to select the element correctly, and then this should work again.
