### ISSUE TITLE
duplicate form IDs

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#86]
![screen shot 2016-09-05 at 12 32 43 pm](https://cloud.githubusercontent.com/assets/4806884/18253710/f6ce98aa-7364-11e6-9697-edafd8ec6a50.png)

**Comment by hallahan** [comment]
We should add some logic to automatically increment a number to the form id if there is a duplicate.

**Comment by mojodna** [comment]
Form IDs are derived from the XLSX filenames (right?), so 694bf1469a970c657ee222333743603040e2658f should have prevented this from becoming a problem in the future after preventing forms from being overwritten.

(I'm not totally convinced by that statement, especially after seeing both "Buildings" and "French buildings" with "buildings" as their form name; @danbjoseph do you know how this came to be?)

**Comment by danbjoseph** [comment]
form_id can be defined on the options tab of the xlsform

**Comment by mojodna** [comment]
c1b51d9 now rejects new forms with duplicate IDs. Rather than automatically resolving them, the error indicates that the user should change the form.
