### ISSUE TITLE
form listing fails

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#87]
![screenshot_20160905-125028](https://cloud.githubusercontent.com/assets/4806884/18254173/14ea929a-7369-11e6-9213-4f93201a2d46.png)

**Comment by hallahan** [comment]
One of the forms is invalid. We need to check for this.

**Comment by danbjoseph** [comment]
this was the offending bit of xml (removed the associated form files)
```
<xform>
<hash>md5:d41d8cd98f00b204e9800998ecf8427e</hash>
<downloadUrl>
http://omkserver.com/omk/data/forms/MG_TEST_06122016.xml
</downloadUrl>
</xform>
```

**Comment by mojodna** [comment]
@danbjoseph that XML fragment was missing, or was present and was what was causing problems?

(In either case, do you remember how it got that way?)

**Comment by danbjoseph** [comment]
i think that was the 25th `<xform>...</xform>` returned in the forms list call and then i deleted the xml file on the server and then things worked? not sure what generated the broken xml file in the first place?

**Comment by mojodna** [comment]
c1b51d9 more aggressively cleans up artifacts that were rejected (and only places them in `data/forms` after they've passed all checks), so broken XML (often 0-length) shouldn't occur.

If you see this again, please re-open along with the offending XLSForm (and XForm, if available).
