### ISSUE TITLE
cards on /omk/pages/forms/ don't handle long filenames gracefully

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#94]
![screen shot 2016-12-05 at 3 41 27 pm](https://cloud.githubusercontent.com/assets/4806884/20901615/52bc8d50-bb01-11e6-8973-a20b34fa1a9f.png)
![screen shot 2016-12-05 at 3 41 22 pm](https://cloud.githubusercontent.com/assets/4806884/20901617/539ac7aa-bb01-11e6-864a-78ff92946e50.png)

**Comment by dalekunce** [comment]
@danbjoseph maybe we could get a short survey name or something from the xls, settings sheet

**Comment by danbjoseph** [comment]
also long form_id
![screen shot 2016-12-05 at 4 02 39 pm](https://cloud.githubusercontent.com/assets/4806884/20902252/4d428a66-bb04-11e6-887f-23f2865d20dc.png)

**Comment by danbjoseph** [comment]
@dalekunce 
- no guaranteed to be that much shorter since the title might just be the filename with spaces instead of underscores
- the title isn't always included on the settings tab
- related, see https://github.com/AmericanRedCross/OpenMapKitServer/issues/53#issuecomment-264975013
